version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py  # Only if you use Sphinx, skip if MkDocs

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
